//
// Generated file, do not edit! Created by nedtool 5.6 from N_PDU.msg.
//

#ifndef __N_PDU_M_H
#define __N_PDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>N_PDU.msg:1</tt> by nedtool.
 * <pre>
 * packet N_PDU
 * {
 *     int id;
 *     int src;
 *     int dst;
 *     simtime_t start;
 * }
 * </pre>
 */
class N_PDU : public ::omnetpp::cPacket
{
  protected:
    int id;
    int src;
    int dst;
    ::omnetpp::simtime_t start;

  private:
    void copy(const N_PDU& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const N_PDU&);

  public:
    N_PDU(const char *name=nullptr, short kind=0);
    N_PDU(const N_PDU& other);
    virtual ~N_PDU();
    N_PDU& operator=(const N_PDU& other);
    virtual N_PDU *dup() const override {return new N_PDU(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getSrc() const;
    virtual void setSrc(int src);
    virtual int getDst() const;
    virtual void setDst(int dst);
    virtual ::omnetpp::simtime_t getStart() const;
    virtual void setStart(::omnetpp::simtime_t start);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const N_PDU& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, N_PDU& obj) {obj.parsimUnpack(b);}


#endif // ifndef __N_PDU_M_H

