//
// Generated file, do not edit! Created by nedtool 5.6 from DL_PDU.msg.
//

#ifndef __DL_PDU_M_H
#define __DL_PDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>DL_PDU.msg:1</tt> by nedtool.
 * <pre>
 * packet DL_PDU
 * {
 *     int pID;
 *     string type;
 *     int src;
 *     int dest;
 * }
 * </pre>
 */
class DL_PDU : public ::omnetpp::cPacket
{
  protected:
    int pID;
    ::omnetpp::opp_string type;
    int src;
    int dest;

  private:
    void copy(const DL_PDU& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DL_PDU&);

  public:
    DL_PDU(const char *name=nullptr, short kind=0);
    DL_PDU(const DL_PDU& other);
    virtual ~DL_PDU();
    DL_PDU& operator=(const DL_PDU& other);
    virtual DL_PDU *dup() const override {return new DL_PDU(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPID() const;
    virtual void setPID(int pID);
    virtual const char * getType() const;
    virtual void setType(const char * type);
    virtual int getSrc() const;
    virtual void setSrc(int src);
    virtual int getDest() const;
    virtual void setDest(int dest);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DL_PDU& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DL_PDU& obj) {obj.parsimUnpack(b);}


#endif // ifndef __DL_PDU_M_H

